#!/bin/sh
echo "Applying Spotless formatting..."

REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT" || exit 1

./mvnw spotless:apply
./mvnw spotless:apply -f Controller/pom.xml
./mvnw spotless:apply -f ServiceForCart/pom.xml
./mvnw spotless:apply -f ServiceForProduct/pom.xml
./mvnw spotless:apply -f ServiceForPay/pom.xml

git add -u