spring:
  application:
    name: marketplace
  datasource:
    url: jdbc:postgresql://localhost:5432/Users
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: 0445b6b15da00f3d3836b6dbe1cd95cdb5e81066f83ffdceed3fbd9ad26d9bc2
    lifetime: 1440
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
server:
  port: 8082