spring:
  application:
    name: marketplace
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  datasource:
    url: jdbc:postgresql://localhost:5432/Users
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: ${JWT_SECRET:}
    lifetime: ${JWT_LIFETIME_MINUTES:1440}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
server:
  port: 8082