spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/Users
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jwt:
    secret: ${JWT_SECRET:}
    lifetime: ${JWT_LIFETIME_MINUTES:1440}
