-- Схема БД Cart: корзина (связка user_id + product_id). ID — IDENTITY, как в Cart.java.

CREATE TABLE IF NOT EXISTS cart (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    product_id  BIGINT
);
