spring:
  application:
    name: serviceForProduct
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081
