spring:
  application:
    name: serviceForProduct
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  datasource:
    url: jdbc:postgresql://localhost:5432/Products
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
app:
  feign:
    user:
      url: http://localhost:8082
server:
  port: 8081
