CREATE TABLE shop_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_user_id BIGINT NOT NULL,
    seller_user_id BIGINT NOT NULL,
    buyer_display_name VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(32) NOT NULL,
    total_rub DOUBLE PRECISION NOT NULL
);

CREATE TABLE shop_order_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    title VARCHAR(512) NOT NULL,
    qty INTEGER NOT NULL,
    line_total_rub DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_shop_order_lines_order FOREIGN KEY (order_id) REFERENCES shop_orders (id) ON DELETE CASCADE
);

CREATE INDEX idx_shop_orders_seller_created ON shop_orders (seller_user_id, created_at DESC);
