name: Build marketplace

on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/build-marketplace.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/build-marketplace.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build
        run: mvn clean verify